### ISSUE TITLE
Error Creating Student AND Employer Account

### ISSUE THREAD

**Issue by stemmlerjs** [UnivJobs/univjobs-back#110]
![image](https://cloud.githubusercontent.com/assets/6892666/20549871/1f3fc792-b0fe-11e6-9656-8676a0a5685a.png)

Server 500 Error on attempting to create a new user on the develop branch.
- I suspect this has something to do with the changes with respect to Julio's work on the email confirmation.

**Comment by stemmlerjs** [comment]
Internal Server Error: /api/register/
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.4/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/rest_framework/generics.py", line 191, in post
    return self.create(request, *args, **kwargs)
  File "/home/ec2-user/univjobs-back/univjobs/student/views.py", line 80, in create
    email.send_confirmation()
  File "/usr/local/lib/python3.4/site-packages/allauth/account/models.py", line 58, in send_confirmation
    confirmation.send(request, signup=signup)
  File "/usr/local/lib/python3.4/site-packages/allauth/account/models.py", line 122, in send
    get_adapter().send_confirmation_mail(request, self, signup)
  File "/usr/local/lib/python3.4/site-packages/allauth/account/adapter.py", line 356, in send_confirmation_mail
    emailconfirmation)
  File "/usr/local/lib/python3.4/site-packages/allauth/account/adapter.py", line 345, in get_email_confirmation_url
    args=[emailconfirmation.key])
  File "/usr/local/lib/python3.4/site-packages/django/core/urlresolvers.py", line 600, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/usr/local/lib/python3.4/site-packages/django/core/urlresolvers.py", line 508, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
django.core.urlresolvers.NoReverseMatch: Reverse for 'account_confirm_email' with arguments '('z49gpkfifzpqxtepzu1zhuu5wcw9orzni370k82w9ms2hm19noctw50xpujlxd4w',)' and keyword arguments '{}' not found. 0 pattern(s) tried: []

**Comment by charlesjavelona** [comment]
Not working on api/register. This does not affect any other url

**Comment by charlesjavelona** [comment]
Update, it actually affects employer register too.

**Comment by charlesjavelona** [comment]
@juliosueiras created a separate branch, see commit https://github.com/UnivJobs/univjobs-back/commit/441ba16b318bbb6b04a3b0bfa6ff459ef4c85902

**Comment by charlesjavelona** [comment]
@juliosueiras created a separate branch, see commit https://github.com/UnivJobs/univjobs-back/commit/441ba16b318bbb6b04a3b0bfa6ff459ef4c85902

**Comment by stemmlerjs** [comment]
Even after reverting back to commit https://github.com/UnivJobs/univjobs-back/commit/441ba16b318bbb6b04a3b0bfa6ff459ef4c85902, **Employer Register** gets a _403 Forbidden_ response saying"

```javascript

{ detail: "Error decoding signature." }
```

**Student Register** works again.

**Comment by charlesjavelona** [comment]
Could you refresh your browser tokens and try again
